server:
  port: 8080
knife4j:
  enableAggregation: true
  cloud: # Cloud模式聚合OpenAPI文档
    enable: true
    routes:
      - name: 测试分组1
        uri: knife4j.xiaominfo.com
        location: /v2/api-docs?group=2.X版本
      - name: 测试分组2
        uri: knife4j.xiaominfo.com
        location: /v2/api-docs?group=3.默认接口
#  nacos:
#    enable: true
#    serviceUrl: http://localhost:10000/eureka/
#    routes:
#      - name: 订单服务
#        serviceName: service-order
#        location: /v2/api-docs?group=default
#        servicePath: /order
#      - name: 用户体系
#        serviceName: service-user
#        location: /aub/v2/api-docs?group=default
#        servicePath: /
#  eureka:
#    enable: true
#    serviceUrl: http://localhost:10000/eureka/
#    routes:
#      - name: 订单服务
#        serviceName: service-order
#        location: /v2/api-docs?group=default
#        servicePath: /order
#      - name: 用户体系
#        serviceName: service-user
#        location: /aub/v2/api-docs?group=default
#        servicePath: /
#  eureka:
#    enable: true
#    serviceUrl: http://localhost:10000/eureka/
#    routes:
#      - name: 订单服务
#        serviceName: service-order
#        location: /v2/api-docs?group=default
#        servicePath: /order
#      - name: 用户体系
#        serviceName: service-user
#        location: /aub/v2/api-docs?group=default
#        servicePath: /
