server:
  port: 40031
spring:
  application:    name: cloud-turbine-stream
  kafka:
    bootstrap-servers:
    - localhost:9092
    client-id: ${spring.application.name}
    consumer:      enable-auto-commit: true
    listener:      type: batch
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
#       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: cloud-turbine-stream
    prefer-ip-address: true     #访问路径可以显示IP地址
management:
  endpoints:
    web:
      exposure:
        # 开启监控端点 "*" hystrix.stream
        include: "*"  endpoint:
    health:      show-details: always    hystrix:      stream:        enabled: false
#hystrix:#  stream:
#    queue:#      destination: hystrixStreamOutput
turbine:
  stream:
    destination: hystrixStreamOutput # springCloudHystrixStream,hystrixStreamOutput,turbineStreamInput#    content-type: application/json
