server:
  port: 40030
spring:
#  kafka:
#    bootstrap-servers:
#    - localhost:9092
  cloud:
    stream:
#      binders:      bindings:
        input:
          destination: stream-demo
        output:      #这里用stream给我们提供的默认output，后面会讲到自定义output        
          destination: stream-demo    #消息发往的目的地            
          content-type: text/plain    #消息发送的格式，接收端不用指定格式，但是发送端要
      kafka:
        binder:          brokers: localhost:9092
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:40000/eureka/
#       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: cloud-turbine
    prefer-ip-address: true     #访问路径可以显示IP地址
management:
  endpoints:
    web:
      exposure:
        # 开启监控端点 "*" hystrix.stream
        include: "*"  endpoint:    hystrix:      stream:        enabled: false
hystrix:  stream:    queue:      destination: hystrixStreamOutput
turbine:  stream:    destination: hystrixStreamOutput
#    content-type: 