server:
  port: 8789

spring:
  application:
    name: admin-server
  security:
    user:
      name: "admin"
      password: "admin"
  boot:    admin:      ui:        title: cloud-admin
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
ribbon:
  eureka:    enabled: true #false不使用Eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
# end::configuration-eureka[]
